- type: job
  id: TaipanAtmosphericsEngineer
  name: job-name-taipan-atmospherics-engineer
  playTimeTracker: JobTaipanAtmosphericsEngineer
  setPreference: false
  description: job-description-taipan-atmospherics-engineer
  startingGear: TaipanAtmosphericsEngineerGear
  icon: "JobIconTaipanAtmosphericsEngineer"
  supervisors: job-supervisors-taipan-technical-supervisor
  canBeAntag: false
  requirements:
  - !type:RoleTimeRequirement
    role: JobAtmosphericTechnician
    time: 18000 #5 hrs
  - !type:RoleTimeRequirement
    role: JobTaipanTechnician
    time: 18000 #5 hrs
  - !type:DepartmentTimeRequirement
    department: Taipan
    time: 36000 #10 hrs
  access:
  - TaipanBasic
  - TaipanMaint
  - TaipanEngineering
  - TaipanAtmospherics
  special:
  - !type:AddImplantSpecial
    implants: [ DeathRattleImplantTaipan ]

- type: startingGear
  id: TaipanAtmosphericsEngineerGear
  equipment:
    ears: ClothingHeadsetTaipan
    shoes: ClothingShoesTaipanBootsWork
    back: ClothingBackpackSyndicate
    socks: ClothingUnderwearSocksTaipanAtmosphericsEngineer
    id: TaipanAtmosphericsEngineerPDA
