- type: job
  id: TaipanBotanist
  name: job-name-taipan-botanist
  playTimeTracker: JobTaipanBotanist
  description: Вы заботитесь о растениях станции и их выращивании, чтобы обеспечить экипаж свежей продукцией.
  startingGear: TaipanBotanistGear
  icon: "JobIconTaipanBotanist"
  supervisors: job-supervisors-taipan-technical-supervisor
  canBeAntag: false
  requirements:
  - !type:RoleTimeRequirement
    role: JobBotanist
    time: 6000
  access:
  - TaipanBasic
  - TaipanService

- type: startingGear
  id: TaipanBotanistGear
  equipment:
    ears: ClothingHeadsetTaipan
    shoes: ClothingShoesBootsLaceup
    back: ClothingBackpackSyndicate
    id: TaipanBotanistPDA
    socks: ClothingUnderwearSocksTaipanBotanist
