- type: job
  id: TaipanBotanist
  name: job-name-taipan-botanist
  playTimeTracker: JobTaipanBotanist
  setPreference: false
  description: job-description-taipan-botanist
  startingGear: TaipanBotanistGear
  icon: "JobIconTaipanBotanist"
  supervisors: job-supervisors-taipan-technical-supervisor
  canBeAntag: false
  requirements:
  - !type:DepartmentTimeRequirement
    department: Civilian
    time: 18000 # 5 hours
  - !type:RoleTimeRequirement
    role: JobBotanist
    time: 3600 # 1 hour
  access:
  - TaipanBasic
  - TaipanService
  special:
  - !type:AddImplantSpecial
    implants: [ DeathRattleImplantTaipan ]

- type: startingGear
  id: TaipanBotanistGear
  equipment:
    ears: ClothingHeadsetTaipan
    shoes: ClothingShoesBootsLaceup
    back: ClothingBackpackSyndicate
    id: TaipanBotanistPDA
    socks: ClothingUnderwearSocksTaipanBotanist
