- type: job
  id: TaipanCargotech
  name: job-name-taipan-cargotech
  playTimeTracker: JobTaipanCargotech
  setPreference: false
  description: job-description-taipan-cargotech
  startingGear: TaipanCargotechGear
  icon: "JobIconTaipanCargotech"
  supervisors: job-name-taipan-technical-supervisor
  canBeAntag: false
  requirements:
  - !type:DepartmentTimeRequirement
    department: Cargo
    time: 18000
  - !type:OverallPlaytimeRequirement
    time: 36000
  access:
  - TaipanMaint
  - TaipanCargo
  special:
  - !type:AddImplantSpecial
    implants: [ DeathRattleImplantTaipan ]

- type: startingGear
  id: TaipanCargotechGear
  equipment:
    ears: ClothingHeadsetTaipan
    shoes: ClothingShoesTaipanBootsWork
    back: ClothingBackpackSyndicate
    id: TaipanCargotechPDA
    socks: ClothingUnderwearSocksTaipanCargotech
