- type: job
  id: TaipanCargotech
  name: job-name-taipan-cargotech
  playTimeTracker: JobTaipanCargotech
  setPreference: false
  description: job-description-taipan-cargotech
  startingGear: TaipanCargotechGear
  icon: "JobIconTaipanCargotech"
  supervisors: job-name-taipan-technical-supervisor
  canBeAntag: false
  requirements:
  - !type:RoleTimeRequirement
    role: JobSalvageSpecialist
    time: 36000 # 10 hours
  access:
  - TaipanMaint
  - TaipanCargo
  special:
  - !type:AddImplantSpecial
    implants: [ DeathRattleImplantTaipan ]

- type: startingGear
  id: TaipanCargotechGear
  equipment:
    ears: ClothingHeadsetTaipan
    shoes: ClothingShoesTaipanBootsWork
    back: ClothingBackpackSyndicate
    id: TaipanCargotechPDA
    socks: ClothingUnderwearSocksTaipanCargotech
