- type: job
  id: TaipanChef
  name: job-name-taipan-chef
  playTimeTracker: JobTaipanChef
  setPreference: false
  description: job-description-taipan-chef
  startingGear: TaipanChefGear
  icon: "JobIconTaipanChef"
  supervisors: job-supervisors-taipan-technical-supervisor
  canBeAntag: false
  requirements:
  - !type:RoleTimeRequirement
    role: Chef
    time: 6000
  access:
  - TaipanBasic
  - TaipanService
  special:
  - !type:AddImplantSpecial
    implants: [ DeathRattleImplantTaipan ]

- type: startingGear
  id: TaipanChefGear
  equipment:
    ears: ClothingHeadsetTaipan
    shoes: ClothingShoesBootsLaceup
    back: ClothingBackpackSyndicate
    id: TaipanChefPDA
    socks: ClothingUnderwearSocksTaipanChef
