- type: job
  id: TaipanChef
  name: job-name-taipan-chef
  playTimeTracker: JobTaipanChef
  description: Вы готовите блюда для экипажа и поддерживаете порядок на кухне станции Тайпан.
  startingGear: TaipanChefGear
  icon: "JobIconTaipanChef"
  supervisors: job-supervisors-taipan-technical-supervisor
  canBeAntag: false
  requirements:
  - !type:RoleTimeRequirement
    role: Chef
    time: 6000
  access:
  - TaipanBasic
  - TaipanService

- type: startingGear
  id: TaipanChefGear
  equipment:
    ears: ClothingHeadsetTaipan
    shoes: ClothingShoesBootsLaceup
    back: ClothingBackpackSyndicate
    id: TaipanChefPDA
    socks: ClothingUnderwearSocksTaipanChef
