- type: job
  id: TaipanCommunicationsOfficer
  name: job-name-taipan-communications-officer
  playTimeTracker: JobTaipanCommunicationsOfficer
  setPreference: false
  description: job-description-taipan-communications-officer
  startingGear: TaipanCommunicationsOfficerGear
  icon: "JobIconTaipanCommunicationsOfficer"
  supervisors: job-supervisors-syndicate
  canBeAntag: false
  requirements:
  - !type:RoleTimeRequirement
    role: JobTaipanRecruit
    time: 36000 # 10 hours
  - !type:DepartmentTimeRequirement
    department: Taipan
    time: 360000 # 100 hours
  access:
  - TaipanCommand
  - TaipanCommunicationsOfficer
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ DeathRattleImplantTaipan ]

- type: startingGear
  id: TaipanCommunicationsOfficerGear
  equipment:
    ears: ClothingHeadsetAltTaipan
    shoes: ClothingShoesBootsSyndieFilled
    id: TaipanCommunicationsOfficerPDA
    back: ClothingBackpackSyndicate
    socks: ClothingUnderwearSocksTaipanCommunicationsOfficer
