- type: job
  id: TaipanMedic
  name: job-name-taipan-medic
  playTimeTracker: JobTaipanMedic
  setPreference: false
  description: job-description-taipan-medic
  startingGear: TaipanMedicGear
  icon: "JobIconTaipanMedic"
  supervisors: job-supervisors-taipan-research-director
  canBeAntag: false
  requirements:
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 36000 # 10 hours
  - !type:RoleTimeRequirement
    role: JobChemist
    time: 18000 # 5 hours
  access:
  - TaipanBasic
  - TaipanMaint
  - TaipanMedical
  special:
  - !type:AddImplantSpecial
    implants: [ DeathRattleImplantTaipan ]

- type: startingGear
  id: TaipanMedicGear
  equipment:
    ears: ClothingHeadsetTaipan
    outerClothing: ClothingOuterTaipanCoatLabMed
    shoes: ClothingShoesColorWhite
    id: TaipanMedicPDA
    back: ClothingBackpackSyndicate
    belt: ClothingBeltMedicalFilled
    socks: ClothingUnderwearSocksTaipanMedic
