- type: job
  id: TaipanResearchDirector
  name: job-name-taipan-research-director
  playTimeTracker: JobTaipanResearchDirector
  setPreference: false
  description: job-description-taipan-research-director
  startingGear: TaipanResearchDirectorGear
  icon: "JobIconTaipanResearchDirector"
  supervisors: job-supervisors-syndicate
  canBeAntag: false
  requirements:
  - !type:DepartmentTimeRequirement
    department: Science
    time: 30000
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 30000
  - !type:OverallPlaytimeRequirement
    time: 150000
  - !type:AgeRequirement
    requiredAge: 24
  access:
  - TaipanBasic
  - TaipanScience
  - TaipanCommand
  - TaipanResearchDirector
  special:
  - !type:AddImplantSpecial
    implants: [ DeathRattleImplantTaipan ]

- type: startingGear
  id: TaipanResearchDirectorGear
  equipment:
    eyes: ClothingEyesGlasses
    ears: ClothingHeadsetAltTaipan
    shoes: ClothingShoesBootsLaceup
    id: TaipanResearchDirectorPDA
    back: ClothingBackpackSyndicate
    socks: ClothingUnderwearSocksTaipanResearchDirector
