- type: job
  id: TaipanResearcher
  name: job-name-taipan-researcher
  playTimeTracker: JobTaipanResearcher
  setPreference: false
  description: job-description-taipan-researcher
  startingGear: TaipanResearcherGear
  icon: "JobIconTaipanResearcher"
  supervisors: job-supervisors-taipan-research-director
  canBeAntag: false
  requirements:
  - !type:DepartmentTimeRequirement
    department: Science
    time: 6000
  access:
  - TaipanBasic
  - TaipanScience
  special:
  - !type:AddImplantSpecial
    implants: [ DeathRattleImplantTaipan ]

- type: startingGear
  id: TaipanResearcherGear
  equipment:
    ears: ClothingHeadsetTaipan
    outerClothing: ClothingOuterTaipanCoatLabResearcher
    shoes: ClothingShoesBootsLaceup
    back: ClothingBackpackSyndicate
    id: TaipanResearcherPDA
    socks: ClothingUnderwearSocksTaipanResearcher
