- type: job
  id: TaipanResearchDirector
  name: job-name-taipan-research-director
  playTimeTracker: JobTaipanResearchDirector
  description: Вы руководите научными проектами и управляете командой ученых на станции Тайпан.
  startingGear: TaipanResearchDirectorGear
  icon: "JobIconTaipanResearchDirector"
  supervisors: job-supervisors-syndicate
  canBeAntag: false
  requirements:
  - !type:DepartmentTimeRequirement
    department: Science
    time: 30000
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 30000
  - !type:OverallPlaytimeRequirement
    time: 150000
  - !type:AgeRequirement
    requiredAge: 24
  access:
  - TaipanBasic
  - TaipanScience
  - TaipanCommand
  - TaipanResearchDirector

- type: startingGear
  id: TaipanResearchDirectorGear
  equipment:
    eyes: ClothingEyesGlasses
    ears: ClothingHeadsetAltTaipan
    shoes: ClothingShoesBootsLaceup
    outerClothing: ClothingOuterTaipanCoatLabResearchDirector
    gloves: ClothingHandsTaipanResearchDirector
    id: TaipanResearchDirectorPDA
    back: ClothingBackpackSyndicate
    socks: ClothingUnderwearSocksTaipanResearchDirector
