- type: job
  id: TaipanResearchDirector
  name: job-name-taipan-research-director
  playTimeTracker: JobTaipanResearchDirector
  setPreference: false
  description: job-description-taipan-research-director
  startingGear: TaipanResearchDirectorGear
  icon: "JobIconTaipanResearchDirector"
  supervisors: job-supervisors-syndicate
  canBeAntag: false
  requirements:
  - !type:DepartmentTimeRequirement
    department: Taipan
    time: 216000 # 60 hours
  - !type:RoleTimeRequirement
    role: JobTaipanResearcher
    time: 72000 # 20 hours
  - !type:RoleTimeRequirement
    role: JobTaipanMedic
    time: 36000 # 10 hours
  access:
  - TaipanMaint
  - TaipanExternal
  - TaipanMedical
  - TaipanScience
  - TaipanCommand
  - TaipanResearchDirector
  special:
  - !type:AddImplantSpecial
    implants: [ DeathRattleImplantTaipan ]

- type: startingGear
  id: TaipanResearchDirectorGear
  equipment:
    eyes: ClothingEyesGlasses
    ears: ClothingHeadsetAltTaipan
    shoes: ClothingShoesBootsLaceup
    id: TaipanResearchDirectorPDA
    back: ClothingBackpackSyndicate
    socks: ClothingUnderwearSocksTaipanResearchDirector
