# No idea why it's in sci but we ball.
# Why is this one file?
- type: job
  id: TaipanAi
  name: job-name-station-ai
  description: job-description-station-ai
  playTimeTracker: JobTaipanAi
  requirements:
    - !type:DepartmentTimeRequirement
      department: Silicon
      time: 72000 # 20 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 72000 # 20 hours
    - !type:OverallPlaytimeRequirement
      time: 648000 # 180 hours
  weight: 10
  canBeAntag: false
  icon: JobIconStationAi
  supervisors: job-supervisors-syndicate
  jobEntity: TaipanAiBrain
  jobPreviewEntity: PlayerTaipanAiPreview
  applyTraits: false
