- type: job
  id: TaipanTechnicalOperationsSupervisor
  name: job-name-taipan-technical-supervisor
  playTimeTracker: JobTaipanTechnicalOperationsSupervisor
  setPreference: false
  description: job-description-taipan-technical-supervisor
  startingGear: TaipanTechnicalOperationsSupervisorGear
  icon: "JobIconTaipanTechnicalOperationsSupervisor"
  supervisors: job-supervisors-syndicate
  canBeAntag: false
  requirements:
  - !type:RoleTimeRequirement
    role: JobTaipanCargotech
    time: 36000 # 10 hours
  - !type:RoleTimeRequirement
    role: JobTaipanAtmosphericsEngineer
    time: 18000 # 5 hours
  - !type:DepartmentTimeRequirement
    department: Taipan
    time: 144000 # 40 hours
  access:
  - TaipanBasic
  - TaipanMaint
  - TaipanExternal
  - TaipanCargo
  - TaipanAtmospherics
  - TaipanEngineering
  - TaipanCommand
  special:
  - !type:AddImplantSpecial
    implants: [ DeathRattleImplantTaipan ]

- type: startingGear
  id: TaipanTechnicalOperationsSupervisorGear
  equipment:
    ears: ClothingHeadsetAltTaipan
    shoes: ClothingShoesBootsLaceup
    id: TaipanTechnicalOperationsSupervisorPDA
    back: ClothingBackpackSyndicate
    socks: ClothingUnderwearSocksTaipanTechnicalOperationsSupervisor
