- type: job
  id: TaipanTechnician
  name: job-name-taipan-technician
  playTimeTracker: JobTaipanTechnician
  setPreference: false
  description: job-description-taipan-technician
  startingGear: TaipanTechnicianGear
  icon: "JobIconTaipanTechnician"
  supervisors: job-supervisors-taipan-technical-supervisor
  canBeAntag: false
  requirements:
  - !type:DepartmentTimeRequirement
    department: Engineering
    time: 12000
  access:
  - TaipanBasic
  - TaipanEngineering
  - TaipanMaint
  special:
  - !type:AddImplantSpecial
    implants: [ DeathRattleImplantTaipan ]

- type: startingGear
  id: TaipanTechnicianGear
  equipment:
    ears: ClothingHeadsetTaipan
    shoes: ClothingShoesTaipanBootsWork
    id: TaipanTechnicianPDA
    back: ClothingBackpackSyndicate
    socks: ClothingUnderwearSocksTaipanTechnician
