- type: startingGear
  id: DeathSquadGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDeathSquad
    back: ClothingDeathSquadronBackpack
    mask: ClothingMaskGasDeathSquad
    eyes: ClothingEyesHudAdvanced
    ears: ClothingHeadsetDeathSquad
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitDeathsquad
    suitstorage: JetpackVoidFilled
    shoes: ClothingShoesBootsMagDeathSquad # DS14-Shoes
    id: DeathsquadPDA
    pocket1: EnergySword
    pocket2: DoubleEmergencyOxygenTankFilled
    belt: ClothingBeltDeathSquadWebbingFilled
    underwearb: ClothingUnderwearBottomBoxersDeathSquad # DS14-Underwear
  storage:
    back:
    - ERTloadoutDeathSquadPrimary
    - ERTloadoutDeathSquadSecondary
    - EnergyShield
    - X4
    - X4
    - SpeedLoaderMagnumAP
    - SpeedLoaderMagnumAP
    - SpeedLoaderMagnumAP
    - SpeedLoaderMagnumAP
    - JawsOfLife
    - PinpointerNuclear
    - WeaponRevolverMatebaAP
    - ClothingEyesPNVAdv
    - CombatMedipen
    - CombatMedipen
    - DesoxyephedrineMedipen
    - DesoxyephedrineMedipen
    - NukeCodePaper

- type: entity
  parent: ClothingBeltSecurityWebbing
  id: ClothingBeltDeathSquadWebbingFilled
  name: штурмовой РПС
  description: РПС члена отряда... какого-то отряда?
