- type: department
  id: Taipan
  name: department-Taipan
  description: department-Taipan-description
  color: "#D381C9"
  roles:
  - TaipanAtmosphericsEngineer
  - TaipanBotanist
  - TaipanCargotech
  - TaipanChef
  - TaipanMedic
  - TaipanResearchDirector
  - TaipanResearcher
  - TaipanCommunicationsOfficer
