- type: playTimeTracker
  id: JobTaipanAtmosphericsEngineer

- type: playTimeTracker
  id: JobTaipanBotanist

- type: playTimeTracker
  id: JobTaipanCargotech

- type: playTimeTracker
  id: JobTaipanChef

- type: playTimeTracker
  id: JobTaipanMedic

- type: playTimeTracker
  id: JobTaipanResearchDirector

- type: playTimeTracker
  id: JobTaipanResearcher

- type: playTimeTracker
  id: JobTaipanCommunicationsOfficer
