- type: entity
  parent: BaseMindRole
  id: MindRoleBankMemory
  name: Bank Memory
  # description: mind-role-fugitive-description
  components:
  - type: MindRole
  - type: BankMemory

# Blob
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleBlob
  name: Blob Role
#  description: mind-role-blob-description
  components:
  - type: MindRole
    antagPrototype: Blob
    exclusiveAntag: true
  - type: BlobRole

# Changeling
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleChangeling
  name: Changeling Role
  #  description: mind-role-changeling-description
  components:
  - type: MindRole
    antagPrototype: Changeling
    exclusiveAntag: true
    roleType: FreeAgent
  - type: ChangelingRole
