- type: latheRecipePack
  id: CBURNAmmoStatic
  recipes:
  - MagazineShotgunIncendiary
  - MagazinePistolSubMachineGunIncendiary
  - MagazinePistolIncendiary
  - MagazineRifleIncendiary
  - MagazineLightRifleIncendiary
  - BoxShotgunIncendiary
  - MagazineBoxPistolIncendiary
  - MagazineBoxRifleIncendiary
  - MagazineBoxLightRifleIncendiary
  - GrenadeIncendiary
