- type: ghostRole
  id: SyndicateKobold
  name: ghost-role-information-syndicate-kobold-reinforcement-name
  description: ghost-role-information-syndicate-kobold-reinforcement-description
  rules: ghost-role-information-syndicate-reinforcement-rules
  entityPrototype: MobKoboldSyndicateAgent
  components:
  - type: GhostRoleNotify
    GroupPrototype: SyndicateGroup

- type: ghostRole
  id: SyndicateKoboldNukeops
  name: ghost-role-information-syndicate-kobold-reinforcement-name
  description: ghost-role-information-syndicate-kobold-reinforcement-description
  rules: ghost-role-information-nukeop-reinforcement-rules
  entityPrototype: MobKoboldSyndicateAgentNukeops
  components:
  - type: GhostRoleNotify
    GroupPrototype: SyndicateGroup

- type: ghostRole
  id: SyndicateMonkey
  name: ghost-role-information-syndicate-monkey-reinforcement-name
  description: ghost-role-information-syndicate-monkey-reinforcement-description
  rules: ghost-role-information-syndicate-reinforcement-rules
  entityPrototype: MobMonkeySyndicateAgent
  components:
  - type: GhostRoleNotify
    GroupPrototype: SyndicateGroup

- type: ghostRole
  id: SyndicateMonkeyNukeops
  name: ghost-role-information-syndicate-monkey-reinforcement-name
  description: ghost-role-information-syndicate-monkey-reinforcement-description
  rules: ghost-role-information-nukeop-reinforcement-rules
  entityPrototype: MobMonkeySyndicateAgentNukeops
  components:
  - type: GhostRoleNotify
    GroupPrototype: SyndicateGroup

- type: ghostRole
  id: SyndicateAgentMedic
  name: ghost-role-information-syndicate-reinforcement-medic-name
  description: ghost-role-information-syndicate-reinforcement-medic-description
  rules: ghost-role-information-syndicate-reinforcement-rules
  entityPrototype: MobHumanSyndicateAgentMedic
  iconPrototype: MedkitCombat
  components:
  - type: GhostRoleNotify
    GroupPrototype: SyndicateGroup

- type: ghostRole
  id: SyndicateAgentSpy
  name: ghost-role-information-syndicate-reinforcement-spy-name
  description: ghost-role-information-syndicate-reinforcement-spy-description
  rules: ghost-role-information-syndicate-reinforcement-rules
  entityPrototype: MobHumanSyndicateAgentSpy
  iconPrototype: ClothingMaskGasVoiceChameleon
  components:
  - type: GhostRoleNotify
    GroupPrototype: SyndicateGroup

- type: ghostRole
  id: SyndicateAgentThief
  name: ghost-role-information-syndicate-reinforcement-thief-name
  description: ghost-role-information-syndicate-reinforcement-thief-description
  rules: ghost-role-information-syndicate-reinforcement-rules
  entityPrototype: MobHumanSyndicateAgentThief
  iconPrototype: SyndicateJawsOfLife
  components:
  - type: GhostRoleNotify
    GroupPrototype: SyndicateGroup